kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "rook-block2"  
  name: datadir-skywalking
  namespace: monitoring
  labels:
    app: skywalking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
